# action.yml
name: Get New Tag Version
description: Check the last tag version released on Github and get the next version to be released
inputs:
  repo_token:
    description: The GitHub token to use for authentication
    required: true
  config_file_path:
    description: Path to configuration file containing the level of the version to be bumped
    required: true
outputs:
  next_version:
    description: The next version to be released

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_token }}
    - ${{ inputs.config_file_path }}
