# action.yml
name: Check consistency of version and tag
description: Check if a version have already been released on GitHub Releases
inputs:
  config_file_path:
    description: Path to configuration file containing the level of the version to be bumped
    required: true
  version_pattern:
    description: >
      Custom regular expression to find version with, defaults to
      `(?i)^(__version__|VERSION) *= *([\'"])v?(?P<version>.+?)\2`
    required: false
outputs:
  next_version:
    description: The next version to be released

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config_file_path }}