# This is a basic workflow to help you get started with Actions

name: Artifact

# Controls when the workflow will run
on: [push]

env:
  ARTIFACT_NAME: myartifact
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Upload the artifact
        uses:  actions/upload-artifact@v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: .

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
