on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request: {}

jobs:
  get_new_version:
    runs-on: ubuntu-latest

    name: A job to get the new semantic version number
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x foobar/config.cfg

      - name: Print the github ref
        run: echo "The github ref is $GITHUB_REF "
      - name: Get the updated version
        id: get_version
        uses: ./
        # uses: enricoGiga/actions-exercises@v2
        with:
          config_file_path: 'foobar/config.cfg'
      # Use the output from the `hello` step
      - name: Get the output time and the input string
        run: echo "The new version is ${{ steps.hello.outputs.next_version }} "