on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Print working directory and github workspace
        run: echo "The working directory is $PWD and the github workspace is $GITHUB_WORKSPACE"
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: 'Enrico the great'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }} "