on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Print working directory and github workspace
        run: echo "The working directory is $PWD "
      - name: Hello world action step
        id: hello
        uses: enricoGiga/actions-exercises/v2
        with:
          who-to-greet: 'Enrico the great'
      # Use the output from the `hello` step
      - name: Get the output time and the input string
        run: echo "Hello ${{ steps.hello.inputs.who-to-greet }}. The time was ${{ steps.hello.outputs.time }} "